//! Typed Tauri commands and events (tauri-specta). This module is the whole
//! surface the WebView can reach. `apps/desktop/src/bindings.ts` is generated
//! from it: debug builds rewrite it at startup, and the `bindings_are_current`
//! test fails when the committed file is stale (regenerate with
//! `VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings`).

mod app;
mod downloads;
mod games;
mod libraries;
pub mod names;
mod servers;
pub mod shortcuts;

use std::path::{Path, PathBuf};

pub(crate) use app::show_main_window;
pub(crate) use servers::spawn_connect;

use crate::events::{
    AuthFinished, ConnectivityChanged, ControllerEvent, GameStarted, GameStopped, InstallFinished,
    InstallProgress, ServerAddRequested, ServerSwitched, ServersChanged, TrustProblem,
};

/// Header of the generated file.
const BINDINGS_HEADER: &str = "// @generated by tauri-specta from apps/desktop/src-tauri. Do not edit.\n\
// Owner: Agent 2. Regenerate: VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings\n";

/// Every command and event the UI can use.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            app::app_ready,
            app::app_info,
            servers::servers_list,
            servers::server_preview,
            servers::server_confirm,
            servers::server_switch,
            servers::server_remove,
            servers::auth_start,
            servers::auth_open_browser,
            servers::auth_submit_code,
            servers::auth_cancel,
            servers::auth_sign_out,
            servers::auth_token_storage,
            libraries::libraries_list,
            libraries::library_pick_folder,
            libraries::library_add,
            libraries::library_set_default,
            libraries::library_remove,
            shortcuts::shortcut_create,
            downloads::download_pause,
            downloads::download_resume,
            downloads::download_retry,
            downloads::download_cancel,
            downloads::download_remove,
            downloads::downloads_reorder,
            games::game_launch,
            games::game_stop,
            crate::updater::updater_status,
            crate::updater::updater_check,
            crate::updater::updater_whats_new,
            crate::updater::updater_install,
            crate::social::commands::social_connection,
            crate::social::commands::social_settings_get,
            crate::social::commands::social_settings_set,
            crate::social::commands::friends_list,
            crate::social::commands::friend_code_create,
            crate::social::commands::friend_request_send,
            crate::social::commands::friend_accept,
            crate::social::commands::friend_decline,
            crate::social::commands::friend_remove,
            crate::social::commands::user_block,
            crate::social::commands::user_unblock,
            crate::social::commands::blocks_list,
            crate::social::commands::user_profile,
            crate::social::commands::conversations_list,
            crate::social::commands::conversation_open_direct,
            crate::social::commands::conversation_create_party,
            crate::social::commands::messages_list,
            crate::social::commands::message_send,
            crate::social::commands::message_retry,
            crate::social::commands::conversation_mark_read,
            crate::social::commands::typing_start,
            crate::social::commands::contact_security,
            crate::social::commands::contact_set_verified,
            crate::social::commands::contact_trust_device,
            crate::social::commands::devices_list,
            crate::social::commands::device_revoke,
            crate::social::commands::invites_list,
            crate::social::commands::invite_send,
            crate::social::commands::invite_accept,
            crate::social::commands::invite_decline,
            crate::social::commands::invite_cancel,
            crate::overlay::commands::package_overlays_list,
            crate::overlay::commands::package_overlay_set,
            crate::overlay::commands::overlay_view,
            crate::overlay::commands::overlay_action
        ])
        .events(tauri_specta::collect_events![
            GameStarted,
            GameStopped,
            InstallProgress,
            InstallFinished,
            ServerSwitched,
            ControllerEvent,
            ServersChanged,
            ConnectivityChanged,
            TrustProblem,
            ServerAddRequested,
            AuthFinished,
            crate::updater::UpdaterStatus,
            crate::social::commands::SocialConnectionChanged,
            crate::social::commands::FriendsChanged,
            crate::social::commands::PresenceChanged,
            crate::social::commands::FriendRequestReceived,
            crate::social::commands::ConversationsChanged,
            crate::social::commands::MessageReceived,
            crate::social::commands::MessageStatusChanged,
            crate::social::commands::Typing,
            crate::social::commands::DeviceNoticeEvent,
            crate::social::commands::InviteReceived,
            crate::social::commands::InviteChanged,
            crate::social::commands::InviteInstallRequested,
            crate::overlay::commands::OverlayViewChanged,
            crate::overlay::commands::OverlayPackageDisabled
        ])
        .error_handling(tauri_specta::ErrorHandlingMode::Result)
        // Byte counts and ids that are u64 in Rust stay below 2^53.
        .dangerously_cast_bigints_to_number()
}

/// Path of the committed bindings file.
pub fn bindings_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/bindings.ts")
}

/// Renders the TypeScript bindings.
pub fn render_bindings(
    builder: &tauri_specta::Builder<tauri::Wry>,
) -> Result<String, BindingsError> {
    let dir = tempfile_dir()?;
    let path = dir.join("bindings.ts");
    builder
        .export(
            specta_typescript::Typescript::default().header(BINDINGS_HEADER),
            &path,
        )
        .map_err(|e| BindingsError::Export(e.to_string()))?;
    let text = std::fs::read_to_string(&path).map_err(BindingsError::Io)?;
    let _ = std::fs::remove_dir_all(&dir);
    Ok(text)
}

fn bindings_equal(committed: &str, generated: &str) -> bool {
    committed.replace("\r\n", "\n") == generated.replace("\r\n", "\n")
}

/// Rewrites `bindings.ts` when it differs (debug builds call this at startup).
pub fn write_bindings_if_changed(
    builder: &tauri_specta::Builder<tauri::Wry>,
) -> Result<bool, BindingsError> {
    let text = render_bindings(builder)?;
    let path = bindings_path();
    if std::fs::read_to_string(&path)
        .ok()
        .is_some_and(|committed| bindings_equal(&committed, &text))
    {
        return Ok(false);
    }
    std::fs::write(&path, text).map_err(BindingsError::Io)?;
    Ok(true)
}

fn tempfile_dir() -> Result<PathBuf, BindingsError> {
    let dir = std::env::temp_dir().join(format!(
        "vgames-bindings-{}-{}",
        std::process::id(),
        uuid::Uuid::now_v7()
    ));
    std::fs::create_dir_all(&dir).map_err(BindingsError::Io)?;
    Ok(dir)
}

#[derive(Debug, thiserror::Error)]
pub enum BindingsError {
    #[error("cannot export the TypeScript bindings: {0}")]
    Export(String),
    #[error("cannot read or write the bindings file")]
    Io(#[source] std::io::Error),
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    fn generated() -> String {
        render_bindings(&specta_builder()).unwrap()
    }

    /// Command names as invoked by the generated bindings.
    fn invoked_commands(bindings: &str) -> BTreeSet<String> {
        // `__TAURI_INVOKE("name"` or `__TAURI_INVOKE<Type>("name"`.
        bindings
            .split("__TAURI_INVOKE")
            .skip(1)
            .filter_map(|rest| {
                let call = rest.split_once("(\"")?;
                let generic = call.0;
                (generic.is_empty() || (generic.starts_with('<') && !generic.contains('\n')))
                    .then(|| call.1.split('"').next())
                    .flatten()
            })
            .map(str::to_owned)
            .collect()
    }

    fn capability_permissions(file: &str) -> BTreeSet<String> {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("capabilities")
            .join(file);
        let json: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        json["permissions"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|p| p.as_str())
            .filter(|p| p.starts_with("allow-"))
            .map(str::to_owned)
            .collect()
    }

    fn permission_names(commands: &[&str]) -> BTreeSet<String> {
        commands
            .iter()
            .map(|c| format!("allow-{}", c.replace('_', "-")))
            .collect()
    }

    #[test]
    fn bindings_are_current() {
        let text = generated();
        if std::env::var_os("VGAMES_UPDATE_BINDINGS").is_some() {
            std::fs::write(bindings_path(), &text).unwrap();
            return;
        }
        let committed = std::fs::read_to_string(bindings_path()).unwrap_or_default();
        assert!(
            bindings_equal(&committed, &text),
            "apps/desktop/src/bindings.ts is stale; run `VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings`"
        );
    }

    #[test]
    fn bindings_comparison_accepts_windows_line_endings_but_not_stale_content() {
        assert!(bindings_equal("one\r\ntwo\r\n", "one\ntwo\n"));
        assert!(!bindings_equal("one\r\nold\r\n", "one\ntwo\n"));
    }

    #[test]
    fn names_list_matches_registered_commands() {
        let registered = invoked_commands(&generated());
        let listed: BTreeSet<String> = names::MAIN_WINDOW_COMMANDS
            .iter()
            .chain(names::OVERLAY_WINDOW_COMMANDS)
            .map(|s| (*s).to_owned())
            .collect();
        assert_eq!(registered, listed, "update src/commands/names.rs");
    }

    #[test]
    fn overlay_window_gets_only_overlay_commands() {
        assert!(
            names::OVERLAY_WINDOW_COMMANDS
                .iter()
                .all(|c| c.starts_with("overlay_"))
        );
        assert!(
            names::MAIN_WINDOW_COMMANDS
                .iter()
                .all(|c| !c.starts_with("overlay_"))
        );
        assert_eq!(
            capability_permissions("overlay.json"),
            permission_names(names::OVERLAY_WINDOW_COMMANDS)
        );
    }

    #[test]
    fn main_window_gets_every_main_command() {
        assert_eq!(
            capability_permissions("main.json"),
            permission_names(names::MAIN_WINDOW_COMMANDS)
        );
    }
}
