// @generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Owner: Agent 2. Regenerate: VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Called by the UI once its first screen has rendered. Shows the main window
	 *  (it starts hidden so the user never sees a blank WebView).
	 */
	appReady: () => typedError<null, CommandError>(__TAURI_INVOKE("app_ready")),
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/** Events */
export const events = {
	controllerEvent: makeEvent<ControllerEvent>("controller-event"),
	gameStarted: makeEvent<GameStarted>("game-started"),
	gameStopped: makeEvent<GameStopped>("game-stopped"),
	installFinished: makeEvent<InstallFinished>("install-finished"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	serverSwitched: makeEvent<ServerSwitched>("server-switched"),
};

/* Types */
/**  Build information for the About screen and diagnostics. */
export type AppInfo = {
	version: string,
	/**  Debug profile name (`VGAMES_PROFILE`), debug builds only. */
	profile: string | null,
	debug_build: boolean,
	/**  `windows`, `linux` or `macos`. */
	os: string,
	/**  `x86_64` or `aarch64`. */
	arch: string,
};

/**  Error payload of every command. */
export type CommandError = {
	code: ErrorCode,
	message: string,
};

/**  What happened to a controller. */
export type ControllerChange = { kind: "connected"; controller: ControllerKind; name: string } | { kind: "disconnected" } | 
/**  Guide/PS held for 1 s (opens the in-game overlay, 05-social §6). */
{ kind: "guide_held" };

/**  A controller event from the input thread. */
export type ControllerEvent = {
	/**  SDL joystick instance id; stable while the pad stays connected. */
	instance_id: number,
	change: ControllerChange,
};

/**  Controller family, as classified by the input thread (07-controllers §2). */
export type ControllerKind = "xinput" | "dualshock4" | "dualsense" | "switch_pro" | "generic";

/**  Stable, closed set of error codes for the UI. */
export type ErrorCode = 
/**  An argument failed validation (bad id, path outside a library, …). */
"invalid_argument" | "not_found" | 
/**  The action conflicts with the current state (already installing, …). */
"conflict" | 
/**  The command is not available in this window or state. */
"not_allowed" | 
/**  Sign-in is required or the session ended. */
"unauthenticated" | 
/**  The server refused the action for this account. */
"forbidden" | 
/**  The server could not be reached. */
"offline" | 
/**  A signature, hash or trust check failed. Never retried automatically. */
"integrity" | 
/**  Not enough disk space. */
"disk_full" | 
/**  Anything else. Details are in the log. */
"internal";

/**  How a game session ended. */
export type GameExit = {
	/**  Exit code of the root process, when the OS reports one. */
	code: number | null,
	/**  Whether the launcher stopped the game at the user's request. */
	stopped_by_user: boolean,
	/**  Duration of this session in seconds. */
	session_seconds: number,
};

/**  A game process tree was spawned. */
export type GameStarted = {
	package: PackageRef,
	/**  OS process id of the tracked root process. */
	pid: number,
};

/**  The whole process tree of a game exited. */
export type GameStopped = {
	package: PackageRef,
	exit: GameExit,
};

/**  An install, update or repair finished (successfully or not). */
export type InstallFinished = {
	package: PackageRef,
	outcome: InstallOutcome,
};

/**  How an install, update or repair ended. */
export type InstallOutcome = { kind: "installed" } | { kind: "cancelled"; kept_partial: boolean } | { kind: "failed"; code: string; message: string };

/**  Phase of an install, update or repair (02-package-format §7). */
export type InstallPhase = "queued" | "verifying_manifest" | "allocating" | "downloading" | "finalizing" | "verifying" | "paused";

/**  Progress of the active install. Emitted at most 4 times per second. */
export type InstallProgress = {
	package: PackageRef,
	phase: InstallPhase,
	/**  Byte counts are below 2^53, so they are safe as JS numbers. */
	bytes_done: number,
	bytes_total: number,
	/**  Exponentially weighted (5 s) transfer rate. */
	bytes_per_second: number,
	eta_seconds: number | null,
	connections: number,
};

/**  A package on a specific server (package ids are only unique per server). */
export type PackageRef = {
	server_id: string,
	package_id: string,
};

/**
 *  The active server changed (`None`: no server is active). Realtime
 *  connections to the previous server must be dropped.
 */
export type ServerSwitched = {
	server_id: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

