// @generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Owner: Agent 2. Regenerate: VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Called by the UI once its first screen has rendered. Shows the main window
	 *  (it starts hidden so the user never sees a blank WebView).
	 */
	appReady: () => typedError<null, CommandError>(__TAURI_INVOKE("app_ready")),
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Every stored server, the active one flagged. A database failure is logged
	 *  and reads as an empty list (the UI then offers to add a server).
	 */
	serversList: () => __TAURI_INVOKE<ServerProfile_Serialize[]>("servers_list"),
	/**
	 *  Fetches `/.well-known/vgames.json`. `expected_fingerprint` comes from a
	 *  `vgames://server/add` link and must match.
	 */
	serverPreview: (url: string, expectedFingerprint: string | null) => typedError<ServerPreview, ServerError>(__TAURI_INVOKE("server_preview", { url, expectedFingerprint })),
	/**  Pins the previewed root key and makes the server active. */
	serverConfirm: (previewId: string) => typedError<ServerProfile_Serialize, ServerError>(__TAURI_INVOKE("server_confirm", { previewId })),
	/**
	 *  Makes a server active, then checks its identity and trust bundle in the
	 *  background (`connectivity-changed` / `trust-problem` report the result).
	 */
	serverSwitch: (serverId: string) => typedError<ServerProfile_Serialize, AppError>(__TAURI_INVOKE("server_switch", { serverId })),
	/**  Signs out and forgets a server (refused while its games are installed). */
	serverRemove: (serverId: string) => typedError<null, AppError>(__TAURI_INVOKE("server_remove", { serverId })),
	/**  Starts Discord sign-in for a server and opens the system browser. */
	authStart: (serverId: string) => typedError<AuthFlow, AuthError>(__TAURI_INVOKE("auth_start", { serverId })),
	authOpenBrowser: (flowId: string) => typedError<null, AuthError>(__TAURI_INVOKE("auth_open_browser", { flowId })),
	/**  The paste-code fallback when the `vgames://` callback cannot reach the launcher. */
	authSubmitCode: (flowId: string, code: string) => typedError<Account, AuthError>(__TAURI_INVOKE("auth_submit_code", { flowId, code })),
	authCancel: (flowId: string) => __TAURI_INVOKE<void>("auth_cancel", { flowId }),
	/**  Revokes this device's session on the server and deletes its tokens. */
	authSignOut: (serverId: string) => typedError<null, AppError>(__TAURI_INVOKE("auth_sign_out", { serverId })),
	authTokenStorage: () => __TAURI_INVOKE<TokenStorage>("auth_token_storage"),
	librariesList: () => typedError<LibraryInfo[], CommandError>(__TAURI_INVOKE("libraries_list")),
	libraryPickFolder: () => typedError<{
	path: string,
	free_bytes: number,
	total_bytes: number,
} | null, LibraryActionError>(__TAURI_INVOKE("library_pick_folder")),
	libraryAdd: (path: string, makeDefault: boolean) => typedError<LibraryInfo, LibraryActionError>(__TAURI_INVOKE("library_add", { path, makeDefault })),
	librarySetDefault: (libraryId: string) => typedError<null, LibraryActionError>(__TAURI_INVOKE("library_set_default", { libraryId })),
	libraryRemove: (libraryId: string) => typedError<null, LibraryRemovalError>(__TAURI_INVOKE("library_remove", { libraryId })),
	/**
	 *  Creates a desktop shortcut that opens `vgames://launch/<package id>`.
	 *  Returns the shortcut's path.
	 */
	shortcutCreate: (pkg: PackageRef) => typedError<string, AppError>(__TAURI_INVOKE("shortcut_create", { pkg })),
	/**  Pre-launch checks, then spawn. `target_id` null = the default target. */
	gameLaunch: (pkg: PackageRef, targetId: string | null) => typedError<null, LaunchError>(__TAURI_INVOKE("game_launch", { pkg, targetId })),
	/**  Ends the game's whole process tree. The UI confirms first. */
	gameStop: (pkg: PackageRef) => typedError<null, AppError>(__TAURI_INVOKE("game_stop", { pkg })),
	/**  Current updater status. */
	updaterStatus: () => __TAURI_INVOKE<UpdaterStatus>("updater_status"),
	/**  Checks for an update now. Refused while a game runs. */
	updaterCheck: () => __TAURI_INVOKE<UpdateCheck>("updater_check"),
	/**  What changed between the installed version and the available update. */
	updaterWhatsNew: () => typedError<WhatsNew, CommandError>(__TAURI_INVOKE("updater_whats_new")),
	/**
	 *  Downloads, verifies (minisign + signed version) and installs the available
	 *  update, then restarts. Waits for downloads to reach a checkpoint; refused
	 *  while a game runs.
	 */
	updaterInstall: () => typedError<null, CommandError>(__TAURI_INVOKE("updater_install")),
	/**  Socket state for the active server. */
	socialConnection: () => __TAURI_INVOKE<SocialConnection>("social_connection"),
	socialSettingsGet: () => typedError<SocialSettings, SocialError>(__TAURI_INVOKE("social_settings_get")),
	socialSettingsSet: (settings: SocialSettings) => typedError<SocialSettings, SocialError>(__TAURI_INVOKE("social_settings_set", { settings })),
	friendsList: () => typedError<FriendList, SocialError>(__TAURI_INVOKE("friends_list")),
	friendCodeCreate: () => typedError<FriendCode, SocialError>(__TAURI_INVOKE("friend_code_create")),
	/**  Sends a request by friend code or user id (`accepted` if they had already asked you). */
	friendRequestSend: (target: FriendTarget) => typedError<Friend, SocialError>(__TAURI_INVOKE("friend_request_send", { target })),
	friendAccept: (userId: string) => typedError<Friend, SocialError>(__TAURI_INVOKE("friend_accept", { userId })),
	friendDecline: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("friend_decline", { userId })),
	/**  Removes a friend or cancels an outgoing request. */
	friendRemove: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("friend_remove", { userId })),
	userBlock: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("user_block", { userId })),
	userUnblock: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("user_unblock", { userId })),
	/**  Users blocked from this install on the active server (kept locally). */
	blocksList: () => typedError<BlockedUser[], SocialError>(__TAURI_INVOKE("blocks_list")),
	userProfile: (userId: string) => typedError<UserSummary, SocialError>(__TAURI_INVOKE("user_profile", { userId })),
	/**  Conversations, most recent first (the cached list when offline). */
	conversationsList: () => typedError<Conversation[], SocialError>(__TAURI_INVOKE("conversations_list")),
	/**  The direct conversation with a friend (created on first use). */
	conversationOpenDirect: (userId: string) => typedError<Conversation, SocialError>(__TAURI_INVOKE("conversation_open_direct", { userId })),
	/**  A party with 1–15 friends. */
	conversationCreateParty: (userIds: string[]) => typedError<Conversation, SocialError>(__TAURI_INVOKE("conversation_create_party", { userIds })),
	/**  Messages oldest first; `limit` 1–200, before the message `before` if given. */
	messagesList: (conversationId: string, before: string | null, limit: number) => typedError<Message[], SocialError>(__TAURI_INVOKE("messages_list", { conversationId, before, limit })),
	/**  Sends a text message (`pending`, then `message-status-changed`). */
	messageSend: (conversationId: string, text: string) => typedError<Message, SocialError>(__TAURI_INVOKE("message_send", { conversationId, text })),
	messageRetry: (messageId: string) => typedError<Message, SocialError>(__TAURI_INVOKE("message_retry", { messageId })),
	conversationMarkRead: (conversationId: string) => typedError<null, SocialError>(__TAURI_INVOKE("conversation_mark_read", { conversationId })),
	/**  "I am typing" (throttled to one frame every 3 s per conversation). */
	typingStart: (conversationId: string) => typedError<null, SocialError>(__TAURI_INVOKE("typing_start", { conversationId })),
	/**  Safety number, verification state and devices of a contact. */
	contactSecurity: (userId: string) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_security", { userId })),
	contactSetVerified: (userId: string, verified: boolean) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_set_verified", { userId, verified })),
	/**  Accepts a contact device's changed key and unblocks sending to it. */
	contactTrustDevice: (userId: string, deviceId: string) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_trust_device", { userId, deviceId })),
	/**  This account's devices on the active server. */
	devicesList: () => typedError<MyDevice[], SocialError>(__TAURI_INVOKE("devices_list")),
	deviceRevoke: (deviceId: string) => typedError<null, SocialError>(__TAURI_INVOKE("device_revoke", { deviceId })),
	/**  Active and recently ended invites, both directions. */
	invitesList: () => typedError<Invite[], SocialError>(__TAURI_INVOKE("invites_list")),
	/**
	 *  Invites a friend. `joinSecret` ("server address / lobby code") stays on this computer and
	 *  reaches the friend only end-to-end encrypted.
	 */
	inviteSend: (toUserId: string, packageId: string, message: string | null, joinSecret: string | null) => typedError<Invite, SocialError>(__TAURI_INVOKE("invite_send", { toUserId, packageId, message, joinSecret })),
	inviteAccept: (inviteId: string) => typedError<Invite, SocialError>(__TAURI_INVOKE("invite_accept", { inviteId })),
	inviteDecline: (inviteId: string) => typedError<Invite, SocialError>(__TAURI_INVOKE("invite_decline", { inviteId })),
	inviteCancel: (inviteId: string) => typedError<Invite, SocialError>(__TAURI_INVOKE("invite_cancel", { inviteId })),
};

/** Events */
export const events = {
	authFinished: makeEvent<AuthFinished>("auth-finished"),
	connectivityChanged: makeEvent<ConnectivityChanged>("connectivity-changed"),
	controllerEvent: makeEvent<ControllerEvent>("controller-event"),
	conversationsChanged: makeEvent<ConversationsChanged>("conversations-changed"),
	deviceNotice: makeEvent<DeviceNoticeEvent>("device-notice"),
	friendRequestReceived: makeEvent<FriendRequestReceived>("friend-request-received"),
	friendsChanged: makeEvent<FriendsChanged>("friends-changed"),
	gameStarted: makeEvent<GameStarted>("game-started"),
	gameStopped: makeEvent<GameStopped>("game-stopped"),
	installFinished: makeEvent<InstallFinished>("install-finished"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	inviteChanged: makeEvent<InviteChanged>("invite-changed"),
	inviteInstallRequested: makeEvent<InviteInstallRequested>("invite-install-requested"),
	inviteReceived: makeEvent<InviteReceived>("invite-received"),
	messageReceived: makeEvent<MessageReceived>("message-received"),
	messageStatusChanged: makeEvent<MessageStatusChanged>("message-status-changed"),
	presenceChanged: makeEvent<PresenceChanged>("presence-changed"),
	serverAddRequested: makeEvent<ServerAddRequested>("server-add-requested"),
	serverSwitched: makeEvent<ServerSwitched>("server-switched"),
	serversChanged: makeEvent<ServersChanged>("servers-changed"),
	socialConnectionChanged: makeEvent<SocialConnectionChanged>("social-connection-changed"),
	trustProblem: makeEvent<TrustProblem>("trust-problem"),
	typing: makeEvent<Typing>("typing"),
	updaterStatus: makeEvent<UpdaterStatus>("updater-status"),
};

/* Types */
/**  The account signed in on a server. */
export type Account = {
	user_id: string,
	username: string,
	display_name: string | null,
	role: Role,
};

/**
 *  Generic error of commands without a more specific error type (the UI's
 *  `AppError`). Messages are English fallbacks; the UI switches on `kind`.
 */
export type AppError = { kind: "network"; detail: string } | { kind: "server"; code: string; message: string } | { kind: "unauthenticated" } | { kind: "not_found" } | { kind: "invalid_input"; field: string; message: string } | { kind: "io"; path: string | null; detail: string } | { kind: "internal"; detail: string };

/**  Build information for the About screen and diagnostics. */
export type AppInfo = {
	version: string,
	/**  Debug profile name (`VGAMES_PROFILE`), debug builds only. */
	profile: string | null,
	debug_build: boolean,
	/**  `windows`, `linux` or `macos`. */
	os: string,
	/**  `x86_64` or `aarch64`. */
	arch: string,
};

export type AuthError = { kind: "registration_closed" } | { kind: "not_allowlisted" } | { kind: "user_disabled" } | { kind: "expired" } | { kind: "invalid_code" } | { kind: "cancelled" } | { kind: "browser_unavailable" } | { kind: "network"; detail: string } | { kind: "server"; code: string; message: string };

/**  A sign-in finished (deep-link callback, pasted code, or cancel). */
export type AuthFinished = {
	flow_id: string,
	outcome: AuthOutcome,
};

/**  A started sign-in, as the UI sees it. */
export type AuthFlow = {
	flow_id: string,
	/**  RFC 3339. */
	expires_at: string,
	/**
	 *  False when the system browser could not be opened; the UI then offers
	 *  the paste-code fallback.
	 */
	browser_opened: boolean,
};

/**  How a sign-in ended (the `AuthFinished` event). */
export type AuthOutcome = { kind: "signed_in"; account: Account } | { kind: "failed"; error: AuthError };

/**  Why an update check or install must wait. */
export type Blocked = "game_running" | "downloads_active";

export type BlockedUser = {
	user_id: string,
	username: string | null,
	blocked_at: string,
};

/**  An install that is busy with something else. */
export type BusyState = "installing" | "updating" | "repairing" | "moving" | "uninstalling";

export type ChangeEntry = {
	type: ChangeType,
	/**  Plain text; the UI renders it as text, never as HTML or Markdown. */
	text: string,
};

/**  Kind of a player-facing change, in the order the dialog groups them. */
export type ChangeType = "added" | "changed" | "fixed" | "removed" | "security";

export type ChosenLibraryFolder = {
	path: string,
	free_bytes: number,
	total_bytes: number,
};

/**  Error payload of every command. */
export type CommandError = {
	code: ErrorCode,
	message: string,
};

/**  Whether the launcher could reach a server on its last attempt. */
export type ConnectivityChanged = {
	server_id: string,
	online: boolean,
};

export type ContactDevice = {
	device_id: string,
	display_name: string | null,
	first_seen_at: string,
	key_fingerprint: string,
	state: ContactDeviceState,
};

export type ContactDeviceState = "trusted" | "new" | "key_changed" | "revoked";

export type ContactSecurity = {
	user_id: string,
	verified: boolean,
	needs_reverification: boolean,
	safety_number: string,
	safety_number_groups: string[],
	devices: ContactDevice[],
};

/**  What happened to a controller. */
export type ControllerChange = { kind: "connected"; controller: ControllerKind; name: string } | { kind: "disconnected" } | 
/**  Guide/PS held for 1 s (opens the in-game overlay, 05-social §6). */
{ kind: "guide_held" };

/**  A controller event from the input thread. */
export type ControllerEvent = {
	/**  SDL joystick instance id; stable while the pad stays connected. */
	instance_id: number,
	change: ControllerChange,
};

/**  Controller family, as classified by the input thread (07-controllers §2). */
export type ControllerKind = "xinput" | "dualshock4" | "dualsense" | "switch_pro" | "generic";

export type Conversation = {
	id: string,
	kind: ConversationKind,
	members: UserSummary[],
	last_message: Message | null,
	unread: number,
	created_at: string,
};

export type ConversationKind = "direct" | "party";

/**  `conversations-changed`: membership, ordering or unread counts changed. */
export type ConversationsChanged = Conversation[];

export type DeviceNotice = { kind: "new_device"; user_id: string; device_id: string; device_name: string } | { kind: "key_changed"; user_id: string; device_id: string } | { kind: "device_revoked"; user_id: string; device_id: string };

/**  `device-notice`: a contact's (or your own) new device, key change or revocation. */
export type DeviceNoticeEvent = {
	conversation_id: string | null,
	notice: DeviceNotice,
};

export type DevicePlatform = "windows" | "linux" | "macos";

/**  Stable, closed set of error codes for the UI. */
export type ErrorCode = 
/**  An argument failed validation (bad id, path outside a library, …). */
"invalid_argument" | "not_found" | 
/**  The action conflicts with the current state (already installing, …). */
"conflict" | 
/**  The command is not available in this window or state. */
"not_allowed" | 
/**  Sign-in is required or the session ended. */
"unauthenticated" | 
/**  The server refused the action for this account. */
"forbidden" | 
/**  The server could not be reached. */
"offline" | 
/**  A signature, hash or trust check failed. Never retried automatically. */
"integrity" | 
/**  Not enough disk space. */
"disk_full" | 
/**  Anything else. Details are in the log. */
"internal";

export type Friend = {
	user: UserSummary,
	state: FriendState,
	presence: Presence | null,
	since: string | null,
};

export type FriendCode = {
	code: string,
	expires_at: string,
};

export type FriendList = {
	friends: Friend[],
	incoming: Friend[],
	outgoing: Friend[],
};

/**  `friend-request-received`: someone sent you a request (toast). */
export type FriendRequestReceived = {
	user: UserSummary,
};

export type FriendState = "accepted" | "incoming" | "outgoing";

export type FriendTarget = { kind: "code"; code: string } | { kind: "user"; user_id: string };

/**  `friends-changed`: the friend list after a resync. */
export type FriendsChanged = FriendList;

/**  How a game session ended. */
export type GameExit = {
	/**  Exit code of the root process, when the OS reports one. */
	code: number | null,
	/**  Whether the launcher stopped the game at the user's request. */
	stopped_by_user: boolean,
	/**  Duration of this session in seconds. */
	session_seconds: number,
};

/**  A game process tree was spawned. */
export type GameStarted = {
	package: PackageRef,
	/**  OS process id of the tracked root process. */
	pid: number,
};

/**  The whole process tree of a game exited. */
export type GameStopped = {
	package: PackageRef,
	exit: GameExit,
};

/**  An install, update or repair finished (successfully or not). */
export type InstallFinished = {
	package: PackageRef,
	outcome: InstallOutcome,
};

/**  How an install, update or repair ended. */
export type InstallOutcome = { kind: "installed" } | { kind: "cancelled"; kept_partial: boolean } | { kind: "failed"; code: string; message: string };

/**  Phase of an install, update or repair (02-package-format §7). */
export type InstallPhase = "queued" | "verifying_manifest" | "allocating" | "downloading" | "finalizing" | "verifying" | "paused";

/**  Progress of the active install. Emitted at most 4 times per second. */
export type InstallProgress = {
	package: PackageRef,
	phase: InstallPhase,
	/**  Byte counts are below 2^53, so they are safe as JS numbers. */
	bytes_done: number,
	bytes_total: number,
	/**  Exponentially weighted (5 s) transfer rate. */
	bytes_per_second: number,
	eta_seconds: number | null,
	connections: number,
};

export type Invite = {
	id: string,
	direction: InviteDirection,
	from: UserSummary,
	to: UserSummary,
	package: InvitePackage,
	state: InviteState,
	progress: number | null,
	message: string | null,
	failure_reason: InviteFailure | null,
	created_at: string,
	updated_at: string,
	expires_at: string,
	has_join_secret: boolean,
};

/**  `invite-changed`: any invite update, both directions. */
export type InviteChanged = Invite;

export type InviteDirection = "incoming" | "outgoing";

export type InviteFailure = "no_build_for_platform" | "install_failed" | "insufficient_space" | "cancelled_by_user";

/**  Why the invite flow opens the install dialog. */
export type InviteInstallReason = "missing" | "outdated";

/**
 *  `invite-install-requested`: open the install or update dialog at once (05-social §5) and
 *  install through the normal commands.
 */
export type InviteInstallRequested = {
	invite_id: string,
	package: PackageRef,
	reason: InviteInstallReason,
};

export type InvitePackage = {
	id: string,
	title: string,
	cover_url: string | null,
};

/**  `invite-received`: a new incoming invite (show the suggestion-style card). */
export type InviteReceived = Invite;

export type InviteState = "pending" | "accepted" | "installing" | "ready" | "joined" | "declined" | "cancelled" | "expired" | "failed";

/**  Why a launch did not start (the UI's `LaunchError`). */
export type LaunchError = { kind: "not_installed" } | { kind: "incomplete" } | { kind: "busy"; state: BusyState } | { kind: "library_offline"; library_path: string } | { kind: "already_running" } | { kind: "target_not_found" } | 
/**  A file no longer matches the signed manifest; "Verify" repairs it. */
{ kind: "integrity"; path: string } | 
/**  The publisher key was revoked; "Verify" fetches a re-signed manifest. */
{ kind: "key_revoked" } | { kind: "compat_unavailable"; detail: string } | { kind: "rate_limited" } | 
/**  A cloud save conflict must be resolved first (A2-T11 sends the conflict). */
{ kind: "save_conflict"; conflict_id: string } | { kind: "io"; detail: string };

/**  Errors expected by the launcher's library screens. */
export type LibraryActionError = { kind: "not_writable" } | { kind: "system_directory" } | { kind: "nested_in_library"; library_path: string } | { kind: "contains_library"; library_path: string } | { kind: "already_added" } | { kind: "not_found" } | { kind: "io"; detail: string };

export type LibraryInfo = {
	id: string,
	path: string,
	label: string | null,
	is_default: boolean,
	online: boolean,
	free_bytes: number | null,
	/**  Reserved for a filesystem capacity measurement; absent when unavailable. */
	total_bytes: number | null,
	install_count: number,
};

export type LibraryRemovalError = { kind: "not_writable" } | { kind: "system_directory" } | { kind: "nested_in_library"; library_path: string } | { kind: "contains_library"; library_path: string } | { kind: "already_added" } | { kind: "not_found" } | { kind: "io"; detail: string } | { kind: "not_empty"; install_count: number };

export type Message = {
	id: string,
	conversation_id: string,
	sender_user_id: string,
	mine: boolean,
	body: MessageBody,
	sent_at: string,
	received_at: string | null,
	status: MessageStatus,
};

export type MessageBody = { kind: "text"; text: string } | { kind: "invite_join"; invite_id: string } | { kind: "notice"; notice: DeviceNotice } | { kind: "unsupported" };

/**  `message-received`: a decrypted incoming message (or a device notice) was stored. */
export type MessageReceived = Message;

export type MessageStatus = "pending" | "sent" | "failed" | "received";

/**  `message-status-changed`: an outgoing message was sent or failed. */
export type MessageStatusChanged = {
	message_id: string,
	conversation_id: string,
	status: MessageStatus,
};

export type MyDevice = {
	id: string,
	display_name: string,
	platform: DevicePlatform,
	current: boolean,
	created_at: string,
	last_seen_at: string | null,
};

/**  A package on a specific server (package ids are only unique per server). */
export type PackageRef = {
	server_id: string,
	package_id: string,
};

export type Presence = {
	status: PresenceStatus,
	package_id: string | null,
	package_title: string | null,
	updated_at: string | null,
};

/**  `presence-changed`: a friend's presence changed. */
export type PresenceChanged = {
	user_id: string,
	presence: Presence,
};

export type PresenceStatus = "online" | "away" | "in_game" | "offline";

export type RegistrationMode = "open" | "allowlist" | "closed";

export type ReleaseNotes = {
	version: string,
	date: string,
	entries: ChangeEntry[],
};

export type Role = "user" | "admin" | "owner";

/**
 *  A `vgames://server/add` link was opened; the UI starts onboarding with
 *  these values (then calls `server_preview(url, fingerprint)`).
 */
export type ServerAddRequested = {
	url: string,
	fingerprint: string,
};

/**  Why a server cannot be previewed or added. */
export type ServerError = { kind: "invalid_url" } | { kind: "insecure_scheme" } | { kind: "unreachable"; detail: string } | { kind: "timeout" } | { kind: "tls"; detail: string } | { kind: "not_vgames" } | { kind: "launcher_too_old"; min_version: string; current_version: string } | { kind: "fingerprint_mismatch"; expected: string; actual: string } | { kind: "already_added"; server_id: string } | { kind: "preview_expired" };

/**  What `server_preview` shows before the user confirms. */
export type ServerPreview = {
	/**  Opaque handle for `server_confirm`; the preview itself stays in Rust. */
	preview_id: string,
	url: string,
	server_id: string,
	name: string,
	motd: string | null,
	fingerprint: string,
	registration_mode: RegistrationMode | null,
	/**  Set when the preview came from a `vgames://server/add` link (already checked equal). */
	expected_fingerprint: string | null,
};

/**  A stored server as the UI sees it. */
export type ServerProfile = ServerProfile_Serialize | ServerProfile_Deserialize;

/**  A stored server as the UI sees it. */
export type ServerProfile_Deserialize = {
	id: string,
	url: string,
	name: string,
	/**  `VG1-XXXX-…` root key fingerprint, pinned when the server was added. */
	fingerprint: string,
	active: boolean,
	account: Account | null,
	/**  RFC 3339. */
	last_connected_at: string | null,
	/**  Set while the server is blocked: the fingerprint it presented instead of the pinned one. */
	blocked_fingerprint?: string | null,
};

/**  A stored server as the UI sees it. */
export type ServerProfile_Serialize = {
	id: string,
	url: string,
	name: string,
	/**  `VG1-XXXX-…` root key fingerprint, pinned when the server was added. */
	fingerprint: string,
	active: boolean,
	account: Account | null,
	/**  RFC 3339. */
	last_connected_at: string | null,
	/**  Set while the server is blocked: the fingerprint it presented instead of the pinned one. */
	blocked_fingerprint?: string | null,
};

/**
 *  The active server changed (`None`: no server is active). Realtime
 *  connections to the previous server must be dropped.
 */
export type ServerSwitched = {
	server_id: string | null,
};

/**  The list of servers or one of their accounts changed; re-read `servers_list`. */
export type ServersChanged = Record<string, never>;

export type SocialConnection = {
	server_id: string | null,
	state: SocialConnectionState,
	retry_at: string | null,
};

/**  `social-connection-changed`: the socket state changed. */
export type SocialConnectionChanged = SocialConnection;

export type SocialConnectionState = "signed_out" | "connecting" | "connected" | "reconnecting";

/**  Why a social command failed. */
export type SocialError = { kind: "not_signed_in" } | { kind: "offline" } | { kind: "not_found" } | { kind: "invalid_input"; field: string; message: string } | { kind: "rate_limited"; retry_after_seconds: number } | { kind: "code_invalid" } | { kind: "limit_reached"; limit: SocialLimit } | { kind: "conflict"; code: string; message: string } | { kind: "key_changed"; user_id: string; device_ids: string[] } | { kind: "server"; code: string; message: string } | { kind: "internal"; detail: string };

export type SocialLimit = "friends" | "pending_requests" | "party_members";

export type SocialSettings = {
	show_current_game: boolean,
	do_not_disturb: boolean,
	overlay_enabled: boolean,
	overlay_hotkey: string,
};

/**  Where session tokens are stored. */
export type TokenStorage = {
	/**
	 *  True when no OS keychain is available and tokens are in a private
	 *  file; Settings shows a persistent warning.
	 */
	fallback_file: boolean,
};

/**
 *  A server presented a root key other than the pinned one. It is blocked
 *  until it presents the pinned key again; there is no "continue anyway".
 */
export type TrustProblem = {
	server_id: string,
	kind: TrustProblemKind,
	server_name: string,
	pinned_fingerprint: string,
	presented_fingerprint: string,
};

export type TrustProblemKind = "fingerprint_mismatch";

/**  `typing`: show "… is typing" for 5 s. */
export type Typing = {
	conversation_id: string,
	user_id: string,
};

/**
 *  Result of a check the user asked for (onboarding's "launcher too old" prompt,
 *  Settings). The banner follows [`UpdaterStatus`] events as usual.
 */
export type UpdateCheck = { kind: "up_to_date" } | { kind: "available"; version: string } | { kind: "failed"; detail: string };

/**  Where the updater is. */
export type UpdaterState = { kind: "idle" } | { kind: "checking" } | { kind: "up_to_date" } | { kind: "available"; version: string; date: string | null } | { kind: "downloading"; version: string; downloaded: number; total: number | null } | 
/**  Installed; the launcher restarts. */
{ kind: "installed"; version: string } | { kind: "failed"; message: string };

/**  Current updater status. Also emitted as an event whenever it changes. */
export type UpdaterStatus = {
	current_version: string,
	state: UpdaterState,
	/**  Why checks and installs are waiting, if they are. */
	blocked: Blocked | null,
};

export type UserSummary = {
	id: string,
	username: string,
	display_name: string | null,
	avatar_url: string | null,
};

/**  What the "What's new" dialog shows. */
export type WhatsNew = {
	/**
	 *  Releases in `(installed, new]`, newest first. A release with no entries
	 *  is shown as [`GENERIC_NOTE`].
	 */
	releases: ReleaseNotes[],
	/**  True when the changelog could not be used and `notes` from `latest.json` are shown. */
	from_latest_notes: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

