// @generated by tauri-specta from apps/desktop/src-tauri. Do not edit.
// Owner: Agent 2. Regenerate: VGAMES_UPDATE_BINDINGS=1 cargo test -p vgames-desktop bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Called by the UI once its first screen has rendered. Shows the main window
	 *  (it starts hidden so the user never sees a blank WebView).
	 */
	appReady: () => typedError<null, CommandError>(__TAURI_INVOKE("app_ready")),
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	librariesList: () => typedError<LibraryInfo[], CommandError>(__TAURI_INVOKE("libraries_list")),
	libraryPickFolder: () => typedError<{
	path: string,
	free_bytes: number,
	total_bytes: number,
} | null, LibraryActionError>(__TAURI_INVOKE("library_pick_folder")),
	libraryAdd: (path: string, makeDefault: boolean) => typedError<LibraryInfo, LibraryActionError>(__TAURI_INVOKE("library_add", { path, makeDefault })),
	librarySetDefault: (libraryId: string) => typedError<null, LibraryActionError>(__TAURI_INVOKE("library_set_default", { libraryId })),
	libraryRemove: (libraryId: string) => typedError<null, LibraryRemovalError>(__TAURI_INVOKE("library_remove", { libraryId })),
	/**  Current updater status. */
	updaterStatus: () => __TAURI_INVOKE<UpdaterStatus>("updater_status"),
	/**  Checks for an update now. Refused while a game runs. */
	updaterCheck: () => __TAURI_INVOKE<UpdateCheck>("updater_check"),
	/**  What changed between the installed version and the available update. */
	updaterWhatsNew: () => typedError<WhatsNew, CommandError>(__TAURI_INVOKE("updater_whats_new")),
	/**
	 *  Downloads, verifies (minisign + signed version) and installs the available
	 *  update, then restarts. Waits for downloads to reach a checkpoint; refused
	 *  while a game runs.
	 */
	updaterInstall: () => typedError<null, CommandError>(__TAURI_INVOKE("updater_install")),
	/**  Socket state for the active server. */
	socialConnection: () => __TAURI_INVOKE<SocialConnection>("social_connection"),
	socialSettingsGet: () => typedError<SocialSettings, SocialError>(__TAURI_INVOKE("social_settings_get")),
	socialSettingsSet: (settings: SocialSettings) => typedError<SocialSettings, SocialError>(__TAURI_INVOKE("social_settings_set", { settings })),
	friendsList: () => typedError<FriendList, SocialError>(__TAURI_INVOKE("friends_list")),
	friendCodeCreate: () => typedError<FriendCode, SocialError>(__TAURI_INVOKE("friend_code_create")),
	/**  Sends a request by friend code or user id (`accepted` if they had already asked you). */
	friendRequestSend: (target: FriendTarget) => typedError<Friend, SocialError>(__TAURI_INVOKE("friend_request_send", { target })),
	friendAccept: (userId: string) => typedError<Friend, SocialError>(__TAURI_INVOKE("friend_accept", { userId })),
	friendDecline: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("friend_decline", { userId })),
	/**  Removes a friend or cancels an outgoing request. */
	friendRemove: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("friend_remove", { userId })),
	userBlock: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("user_block", { userId })),
	userUnblock: (userId: string) => typedError<null, SocialError>(__TAURI_INVOKE("user_unblock", { userId })),
	/**  Users blocked from this install on the active server (kept locally). */
	blocksList: () => typedError<BlockedUser[], SocialError>(__TAURI_INVOKE("blocks_list")),
	userProfile: (userId: string) => typedError<UserSummary, SocialError>(__TAURI_INVOKE("user_profile", { userId })),
	/**  Conversations, most recent first (the cached list when offline). */
	conversationsList: () => typedError<Conversation[], SocialError>(__TAURI_INVOKE("conversations_list")),
	/**  The direct conversation with a friend (created on first use). */
	conversationOpenDirect: (userId: string) => typedError<Conversation, SocialError>(__TAURI_INVOKE("conversation_open_direct", { userId })),
	/**  A party with 1–15 friends. */
	conversationCreateParty: (userIds: string[]) => typedError<Conversation, SocialError>(__TAURI_INVOKE("conversation_create_party", { userIds })),
	/**  Messages oldest first; `limit` 1–200, before the message `before` if given. */
	messagesList: (conversationId: string, before: string | null, limit: number) => typedError<Message[], SocialError>(__TAURI_INVOKE("messages_list", { conversationId, before, limit })),
	/**  Sends a text message (`pending`, then `message-status-changed`). */
	messageSend: (conversationId: string, text: string) => typedError<Message, SocialError>(__TAURI_INVOKE("message_send", { conversationId, text })),
	messageRetry: (messageId: string) => typedError<Message, SocialError>(__TAURI_INVOKE("message_retry", { messageId })),
	conversationMarkRead: (conversationId: string) => typedError<null, SocialError>(__TAURI_INVOKE("conversation_mark_read", { conversationId })),
	/**  "I am typing" (throttled to one frame every 3 s per conversation). */
	typingStart: (conversationId: string) => typedError<null, SocialError>(__TAURI_INVOKE("typing_start", { conversationId })),
	/**  Safety number, verification state and devices of a contact. */
	contactSecurity: (userId: string) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_security", { userId })),
	contactSetVerified: (userId: string, verified: boolean) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_set_verified", { userId, verified })),
	/**  Accepts a contact device's changed key and unblocks sending to it. */
	contactTrustDevice: (userId: string, deviceId: string) => typedError<ContactSecurity, SocialError>(__TAURI_INVOKE("contact_trust_device", { userId, deviceId })),
	/**  This account's devices on the active server. */
	devicesList: () => typedError<MyDevice[], SocialError>(__TAURI_INVOKE("devices_list")),
	deviceRevoke: (deviceId: string) => typedError<null, SocialError>(__TAURI_INVOKE("device_revoke", { deviceId })),
};

/** Events */
export const events = {
	controllerEvent: makeEvent<ControllerEvent>("controller-event"),
	conversationsChanged: makeEvent<ConversationsChanged>("conversations-changed"),
	deviceNotice: makeEvent<DeviceNoticeEvent>("device-notice"),
	friendRequestReceived: makeEvent<FriendRequestReceived>("friend-request-received"),
	friendsChanged: makeEvent<FriendsChanged>("friends-changed"),
	gameStarted: makeEvent<GameStarted>("game-started"),
	gameStopped: makeEvent<GameStopped>("game-stopped"),
	installFinished: makeEvent<InstallFinished>("install-finished"),
	installProgress: makeEvent<InstallProgress>("install-progress"),
	messageReceived: makeEvent<MessageReceived>("message-received"),
	messageStatusChanged: makeEvent<MessageStatusChanged>("message-status-changed"),
	presenceChanged: makeEvent<PresenceChanged>("presence-changed"),
	serverSwitched: makeEvent<ServerSwitched>("server-switched"),
	socialConnectionChanged: makeEvent<SocialConnectionChanged>("social-connection-changed"),
	typing: makeEvent<Typing>("typing"),
	updaterStatus: makeEvent<UpdaterStatus>("updater-status"),
};

/* Types */
/**  Build information for the About screen and diagnostics. */
export type AppInfo = {
	version: string,
	/**  Debug profile name (`VGAMES_PROFILE`), debug builds only. */
	profile: string | null,
	debug_build: boolean,
	/**  `windows`, `linux` or `macos`. */
	os: string,
	/**  `x86_64` or `aarch64`. */
	arch: string,
};

/**  Why an update check or install must wait. */
export type Blocked = "game_running" | "downloads_active";

export type BlockedUser = {
	user_id: string,
	username: string | null,
	blocked_at: string,
};

export type ChangeEntry = {
	type: ChangeType,
	/**  Plain text; the UI renders it as text, never as HTML or Markdown. */
	text: string,
};

/**  Kind of a player-facing change, in the order the dialog groups them. */
export type ChangeType = "added" | "changed" | "fixed" | "removed" | "security";

export type ChosenLibraryFolder = {
	path: string,
	free_bytes: number,
	total_bytes: number,
};

/**  Error payload of every command. */
export type CommandError = {
	code: ErrorCode,
	message: string,
};

export type ContactDevice = {
	device_id: string,
	display_name: string | null,
	first_seen_at: string,
	key_fingerprint: string,
	state: ContactDeviceState,
};

export type ContactDeviceState = "trusted" | "new" | "key_changed" | "revoked";

export type ContactSecurity = {
	user_id: string,
	verified: boolean,
	needs_reverification: boolean,
	safety_number: string,
	safety_number_groups: string[],
	devices: ContactDevice[],
};

/**  What happened to a controller. */
export type ControllerChange = { kind: "connected"; controller: ControllerKind; name: string } | { kind: "disconnected" } | 
/**  Guide/PS held for 1 s (opens the in-game overlay, 05-social §6). */
{ kind: "guide_held" };

/**  A controller event from the input thread. */
export type ControllerEvent = {
	/**  SDL joystick instance id; stable while the pad stays connected. */
	instance_id: number,
	change: ControllerChange,
};

/**  Controller family, as classified by the input thread (07-controllers §2). */
export type ControllerKind = "xinput" | "dualshock4" | "dualsense" | "switch_pro" | "generic";

export type Conversation = {
	id: string,
	kind: ConversationKind,
	members: UserSummary[],
	last_message: Message | null,
	unread: number,
	created_at: string,
};

export type ConversationKind = "direct" | "party";

/**  `conversations-changed`: membership, ordering or unread counts changed. */
export type ConversationsChanged = Conversation[];

export type DeviceNotice = { kind: "new_device"; user_id: string; device_id: string; device_name: string } | { kind: "key_changed"; user_id: string; device_id: string } | { kind: "device_revoked"; user_id: string; device_id: string };

/**  `device-notice`: a contact's (or your own) new device, key change or revocation. */
export type DeviceNoticeEvent = {
	conversation_id: string | null,
	notice: DeviceNotice,
};

export type DevicePlatform = "windows" | "linux" | "macos";

/**  Stable, closed set of error codes for the UI. */
export type ErrorCode = 
/**  An argument failed validation (bad id, path outside a library, …). */
"invalid_argument" | "not_found" | 
/**  The action conflicts with the current state (already installing, …). */
"conflict" | 
/**  The command is not available in this window or state. */
"not_allowed" | 
/**  Sign-in is required or the session ended. */
"unauthenticated" | 
/**  The server refused the action for this account. */
"forbidden" | 
/**  The server could not be reached. */
"offline" | 
/**  A signature, hash or trust check failed. Never retried automatically. */
"integrity" | 
/**  Not enough disk space. */
"disk_full" | 
/**  Anything else. Details are in the log. */
"internal";

export type Friend = {
	user: UserSummary,
	state: FriendState,
	presence: Presence | null,
	since: string | null,
};

export type FriendCode = {
	code: string,
	expires_at: string,
};

export type FriendList = {
	friends: Friend[],
	incoming: Friend[],
	outgoing: Friend[],
};

/**  `friend-request-received`: someone sent you a request (toast). */
export type FriendRequestReceived = {
	user: UserSummary,
};

export type FriendState = "accepted" | "incoming" | "outgoing";

export type FriendTarget = { kind: "code"; code: string } | { kind: "user"; user_id: string };

/**  `friends-changed`: the friend list after a resync. */
export type FriendsChanged = FriendList;

/**  How a game session ended. */
export type GameExit = {
	/**  Exit code of the root process, when the OS reports one. */
	code: number | null,
	/**  Whether the launcher stopped the game at the user's request. */
	stopped_by_user: boolean,
	/**  Duration of this session in seconds. */
	session_seconds: number,
};

/**  A game process tree was spawned. */
export type GameStarted = {
	package: PackageRef,
	/**  OS process id of the tracked root process. */
	pid: number,
};

/**  The whole process tree of a game exited. */
export type GameStopped = {
	package: PackageRef,
	exit: GameExit,
};

/**  An install, update or repair finished (successfully or not). */
export type InstallFinished = {
	package: PackageRef,
	outcome: InstallOutcome,
};

/**  How an install, update or repair ended. */
export type InstallOutcome = { kind: "installed" } | { kind: "cancelled"; kept_partial: boolean } | { kind: "failed"; code: string; message: string };

/**  Phase of an install, update or repair (02-package-format §7). */
export type InstallPhase = "queued" | "verifying_manifest" | "allocating" | "downloading" | "finalizing" | "verifying" | "paused";

/**  Progress of the active install. Emitted at most 4 times per second. */
export type InstallProgress = {
	package: PackageRef,
	phase: InstallPhase,
	/**  Byte counts are below 2^53, so they are safe as JS numbers. */
	bytes_done: number,
	bytes_total: number,
	/**  Exponentially weighted (5 s) transfer rate. */
	bytes_per_second: number,
	eta_seconds: number | null,
	connections: number,
};

/**  Errors expected by the launcher's library screens. */
export type LibraryActionError = { kind: "not_writable" } | { kind: "system_directory" } | { kind: "nested_in_library"; library_path: string } | { kind: "contains_library"; library_path: string } | { kind: "already_added" } | { kind: "not_found" } | { kind: "io"; detail: string };

export type LibraryInfo = {
	id: string,
	path: string,
	label: string | null,
	is_default: boolean,
	online: boolean,
	free_bytes: number | null,
	/**  Reserved for a filesystem capacity measurement; absent when unavailable. */
	total_bytes: number | null,
	install_count: number,
};

export type LibraryRemovalError = { kind: "not_writable" } | { kind: "system_directory" } | { kind: "nested_in_library"; library_path: string } | { kind: "contains_library"; library_path: string } | { kind: "already_added" } | { kind: "not_found" } | { kind: "io"; detail: string } | { kind: "not_empty"; install_count: number };

export type Message = {
	id: string,
	conversation_id: string,
	sender_user_id: string,
	mine: boolean,
	body: MessageBody,
	sent_at: string,
	received_at: string | null,
	status: MessageStatus,
};

export type MessageBody = { kind: "text"; text: string } | { kind: "invite_join"; invite_id: string } | { kind: "notice"; notice: DeviceNotice } | { kind: "unsupported" };

/**  `message-received`: a decrypted incoming message (or a device notice) was stored. */
export type MessageReceived = Message;

export type MessageStatus = "pending" | "sent" | "failed" | "received";

/**  `message-status-changed`: an outgoing message was sent or failed. */
export type MessageStatusChanged = {
	message_id: string,
	conversation_id: string,
	status: MessageStatus,
};

export type MyDevice = {
	id: string,
	display_name: string,
	platform: DevicePlatform,
	current: boolean,
	created_at: string,
	last_seen_at: string | null,
};

/**  A package on a specific server (package ids are only unique per server). */
export type PackageRef = {
	server_id: string,
	package_id: string,
};

export type Presence = {
	status: PresenceStatus,
	package_id: string | null,
	package_title: string | null,
	updated_at: string | null,
};

/**  `presence-changed`: a friend's presence changed. */
export type PresenceChanged = {
	user_id: string,
	presence: Presence,
};

export type PresenceStatus = "online" | "away" | "in_game" | "offline";

export type ReleaseNotes = {
	version: string,
	date: string,
	entries: ChangeEntry[],
};

/**
 *  The active server changed (`None`: no server is active). Realtime
 *  connections to the previous server must be dropped.
 */
export type ServerSwitched = {
	server_id: string | null,
};

export type SocialConnection = {
	server_id: string | null,
	state: SocialConnectionState,
	retry_at: string | null,
};

/**  `social-connection-changed`: the socket state changed. */
export type SocialConnectionChanged = SocialConnection;

export type SocialConnectionState = "signed_out" | "connecting" | "connected" | "reconnecting";

/**  Why a social command failed. */
export type SocialError = { kind: "not_signed_in" } | { kind: "offline" } | { kind: "not_found" } | { kind: "invalid_input"; field: string; message: string } | { kind: "rate_limited"; retry_after_seconds: number } | { kind: "code_invalid" } | { kind: "limit_reached"; limit: SocialLimit } | { kind: "conflict"; code: string; message: string } | { kind: "key_changed"; user_id: string; device_ids: string[] } | { kind: "server"; code: string; message: string } | { kind: "internal"; detail: string };

export type SocialLimit = "friends" | "pending_requests" | "party_members";

export type SocialSettings = {
	show_current_game: boolean,
	do_not_disturb: boolean,
	overlay_enabled: boolean,
	overlay_hotkey: string,
};

/**  `typing`: show "… is typing" for 5 s. */
export type Typing = {
	conversation_id: string,
	user_id: string,
};

/**
 *  Result of a check the user asked for (onboarding's "launcher too old" prompt,
 *  Settings). The banner follows [`UpdaterStatus`] events as usual.
 */
export type UpdateCheck = { kind: "up_to_date" } | { kind: "available"; version: string } | { kind: "failed"; detail: string };

/**  Where the updater is. */
export type UpdaterState = { kind: "idle" } | { kind: "checking" } | { kind: "up_to_date" } | { kind: "available"; version: string; date: string | null } | { kind: "downloading"; version: string; downloaded: number; total: number | null } | 
/**  Installed; the launcher restarts. */
{ kind: "installed"; version: string } | { kind: "failed"; message: string };

/**  Current updater status. Also emitted as an event whenever it changes. */
export type UpdaterStatus = {
	current_version: string,
	state: UpdaterState,
	/**  Why checks and installs are waiting, if they are. */
	blocked: Blocked | null,
};

export type UserSummary = {
	id: string,
	username: string,
	display_name: string | null,
	avatar_url: string | null,
};

/**  What the "What's new" dialog shows. */
export type WhatsNew = {
	/**
	 *  Releases in `(installed, new]`, newest first. A release with no entries
	 *  is shown as [`GENERIC_NOTE`].
	 */
	releases: ReleaseNotes[],
	/**  True when the changelog could not be used and `notes` from `latest.json` are shown. */
	from_latest_notes: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

